ingress:
  enabled: true
  hosts:
  - host: "localhost"
    paths:
      - path: /
        pathType: "ImplementationSpecific"

httpd: 
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.25"
    limits:
      memory: "1Gi"
      cpu: "0.5"

redcap:
  install:
    enabled: true
    version: "15.0.27"

    communityAuth:
      existingSecret: "redcap-community-credentials"

  config:
    logAllErrors: "TRUE"

  resources:
    requests:
      memory: "2Gi"
      cpu: "0.5"
    limits:
      memory: "4Gi"
      cpu: "2"

mysql:
  primary:
    resources:
      requests:
        memory: "2Gi"
        cpu: "0.5"
      limits:
        memory: "4Gi"
        cpu: "2"

backupJob:
  enabled: false
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.25"
    limits:
      memory: "1Gi"
      cpu: "0.5"

restoreJob:
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.25"
    limits:
      memory: "1Gi"
      cpu: "0.5"