{{- if and (.Values.httpd.enabled) (.Values.networkPolicies.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-httpd-egress
spec:
  podSelector:
    matchLabels:
      {{ include "httpd.networkPolicy.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{ include "redcap.networkPolicy.selectorLabels" . | nindent 12 }}
    ports:
      - protocol: TCP
        port: {{ .Values.services.redcap.port }}

  # allow DNS resolution
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
{{- end }}