{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-restore-job-egress
spec:
  podSelector:
    matchLabels:
      {{ include "redcap.restoreJob.networkPolicy.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - to:
      ports:
        - protocol: TCP
          port: 443
    - to:
      - podSelector:
          matchLabels:
            {{- range $labelKey, $labelValue := .Values.mysql.primary.podLabels }}
              {{ $labelKey | nindent 12 }}: {{ $labelValue }}
            {{- end }}
      ports:
        - protocol: TCP
          port: {{ default 3306 .Values.mysql.primary.service.port.mysql }}

    # allow DNS resolution
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
{{- end }}
