{{- if and (not .Values.mysql.enabled) (empty .Values.redcap.config.database.auth.password.secretKeyRef.name ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.secrets.password.name" . }}
type: Opaque
data: 
  {{ include "mysql.secrets.password.key" . }}: {{ required "You need to specify REDCap database password, as you didn't enabled the MySQL database embedded in this chart, nor provided a reference to an external Secret containing your database password!" .Values.redcap.config.database.auth.password.value }}
{{- end }}
