{{- if .Values.services.redcap.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redcap.serviceName" . }}
  labels:
    {{- include "redcap.labels" . | nindent 4 }}
  {{- with .Values.services.redcap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.redcap.type }}
  ports:
    - port: 9000
      targetPort: 9000
      protocol: "TCP"

  selector:
    {{- include "redcap.selectorLabels" . | nindent 4 }}
{{- end }}
